#!/usr/bin/env python3

import os
import subprocess
import argparse
import yaml


def is_brew_installed() -> bool:
    """
    Check if homebrew package manager is installed.
    """

    result = subprocess.run("brew --version", capture_output=True, shell=True)

    if result.returncode != 0:
        return False

    version = result.stdout.decode("utf-8").strip().split(" ")[1]
    print(f"homebrew version {version}")
    return True


def get_operating_system() -> str:
    os_name = os.uname().sysname
    if os_name not in ["Darwin", "Linux"]:
        print("only macOS and Linux are supported")
        exit(1)
    return os_name


def get_package_manager(os_name: str) -> str:
    if os_name == "Darwin":
        if is_brew_installed():
            return "brew"
        else:
            print("error: homebrew not installed")
            exit(1)
    elif os_name == "Linux":
        if os.uname().nodename == "fedora":
            return "dnf"
    else:
        print("unknown operating system:", os_name)
        exit(2)


def check_python_installation() -> None:
    result = subprocess.run("python3 --version", capture_output=True, shell=True)
    if result.returncode != 0:
        print("error: no python3 found")
        exit(2)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="setup", description="leo's programming environment"
    )
    parser.add_argument("-x", "--develop", action="store_true")

    args = parser.parse_args()

    if args.develop:
        os_name = get_operating_system()
        print(f"dev: operating system: {os_name}")
        package_manager = get_package_manager(os_name)
        print(f"dev: package manager: {package_manager}")

    with open("me.yml", "r") as f:
        config_data = yaml.safe_load(f)

    for lang in config_data['languages']:
        print("debug: checking", lang)
        if lang == 'python':
            check_python_installation()
        else:
            print("warning: unrecognized language:", lang)

    for tool in config_data['tools']:
        print("debug: checking", tool['name'])